version: '3.8'

services:
  api:
    build: ./api
    ports:
      - '5000:5000'
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydatabase
      NODE_ENV: dev
    restart: always

  db:
    image: postgres:13.15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    networks:
      - mynetwork
    ports:
      - '5432:5432'
    restart: always
    
  web_client:
    build: ./web_client
    ports:
      - '8081:80'
    networks:
      - mynetwork
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mynetwork
    depends_on:
      - web_client

networks:
  mynetwork:
    driver: bridge
